### ISSUE TITLE
How triangulation is built

### ISSUE THREAD

**Issue by rubenspecogna** [copyrite/packit#1]
dear Tatu, thank you for sharing your program. Could you please give me additional information on what do you mean by triangulation in the packit input? For me, triangulation is a set of nodes with their x and y coordinates and a list of triangles, each of them being a list of the integer labels of three nodes. Thank you in advance and best regards. Ruben

**Comment by copyrite** [comment]
Dear Ruben,

Thank you for your interest in the repo! You're on the right track by noting that triangulations have a close relationship with lists of integer labels. However, in CirclePack problems the requirement of also providing initial positions for nodes is dropped. This is because a basic CirclePack problem -- one that Packit solves -- boils down to finding a mapping from nodes to circle radii.

If I'm reading my old code correctly, you can enter such a triangulation's combinatorics as an n-by-3 matrix. Other formats are accepted too, but this sounds like it best fits your use case. Does this help? Please let me know if I can assist you with anything else or if you have other feedback!

**Comment by rubenspecogna** [comment]
dear Tatu, thank you for the rapid answer. I would love to produce the packing inside a circle sector. So given a polygonal approximation of the sector boundary (i.e. a list of segments), it is not clear to me how to produce the triangles of the triangulation to be used as an input for packit. What each row of the n-by-3 matrix represents? Are just the three labels of the vertices of the triangle? But then, how to pass the metric information? Thank you in advance for your time, Ruben

**Comment by copyrite** [comment]
Let me first cite a source: https://www.math.utk.edu/~kens/Notices_article.pdf

Is figure 6 roughly what you're trying to do? Omega would be your a circle sector. If so, you'll want to apply a "penny packing" (as in the figure) or another sufficiently regular packing to approximate the domain. From this process you will obtain some combinatorics as a list of adjacent, oriented triangles which you can use as an input to Packit.

> What each row of the n-by-3 matrix represents? Are just the three labels of the vertices of the triangle?

This is correct.

Best regards,
Tatu

**Comment by rubenspecogna** [comment]
dear Tatu,

yes. I need something like 
https://mathworld.wolfram.com/images/eps-gif/CirclesInTriangles_1000.gif 
for a triangle container, but using a circle sector as a container.

What is still not clear to me is how to represent the metric information 
of the container. You probably mean that it is contained inside the 
combinatorics, in the sense that all triangles of the triangulation are 
assumed to be equilateral?

Sorry for asking so many details, but I would love to make it work.

Thank you once more and best regards,

Ruben


Il 14/07/2020 19:31, Tatu Leinonen ha scritto:

**Comment by copyrite** [comment]
If the setting is like the one presented in the article I linked, that is we penny-pack the domain Omega, then yes the triangulation is implied to be equilateral.

Just to make sure, if you don't mind: Are you trying to [fit equally sized circles in a domain](https://mathworld.wolfram.com/CirclePacking.html), or [adjust the sizes of circles under given combinatorics until they satisfy certain constraints](https://www.math.utk.edu/~kens/Notices_article.pdf)? This program will only do the latter.

**Comment by rubenspecogna** [comment]
Thank you Tatu. In fact I need to fit equally sized circles in a 
domain... Thank you anyway!


Il 15/07/2020 20:16, Tatu Leinonen ha scritto:
